import { dlopen, FFIType, suffix } from "bun:ffi";

import sdl2_lib from "./lib/SDL2.dll" with { type: "file" };

export const {
    SDL_Init,
    SDL_GameControllerOpen,
    SDL_GameControllerUpdate,
    SDL_GameControllerGetButton,
    SDL_GameControllerGetAxis,
    SDL_GameControllerSetLED,
    SDL_PumpEvents,
    SDL_SetHint,
    SDL_GameControllerSetSensorEnabled,
    SDL_GameControllerRumble,
    SDL_Delay
} = dlopen(sdl2_lib, {
    SDL_Init: {
        args: ["u32"],
        returns: "i32",
    },
    SDL_GameControllerOpen: {
        args: ["i32"],
        returns: "ptr",
    },
    SDL_GameControllerUpdate: {
        args: []
    },
    SDL_PumpEvents: {
        args: []
    },
    SDL_GameControllerGetButton: {
        args: ["ptr", 'i32'],
        returns: "u8",
    },
    SDL_GameControllerGetAxis: {
        args: ["ptr", 'i32'],
        returns: "i16",
    },
    SDL_GameControllerSetLED: {
        args: ["ptr", 'u8', 'u8', 'u8'],
        returns: "i32",
    },
    SDL_SetHint: {
        args: ["cstring", 'cstring'],
        returns: "i32",
    },
    SDL_GameControllerSetSensorEnabled: {
        args: ["ptr", 'i32', 'cstring'],
        returns: "i32",
    },
    SDL_GameControllerRumble: {
        args: ["ptr", 'u16', 'u16', 'u32'],
        returns: "i32",
    },
    SDL_Delay: {
        args: ['u32'],
        threadsafe: true
    },
}).symbols

export const SDL_CONTROLLER_BUTTON_INVALID = -1;
export const SDL_CONTROLLER_BUTTON_A = 0;
export const SDL_CONTROLLER_BUTTON_B = 1;
export const SDL_CONTROLLER_BUTTON_X = 2;
export const SDL_CONTROLLER_BUTTON_Y = 3;
export const SDL_CONTROLLER_BUTTON_BACK = 4;
export const SDL_CONTROLLER_BUTTON_GUIDE = 5;
export const SDL_CONTROLLER_BUTTON_START = 6;
export const SDL_CONTROLLER_BUTTON_LEFTSTICK = 7;
export const SDL_CONTROLLER_BUTTON_RIGHTSTICK = 8;
export const SDL_CONTROLLER_BUTTON_LEFTSHOULDER = 9;
export const SDL_CONTROLLER_BUTTON_RIGHTSHOULDER = 10;
export const SDL_CONTROLLER_BUTTON_DPAD_UP = 11;
export const SDL_CONTROLLER_BUTTON_DPAD_DOWN = 12;
export const SDL_CONTROLLER_BUTTON_DPAD_LEFT = 13;
export const SDL_CONTROLLER_BUTTON_DPAD_RIGHT = 14;
export const SDL_CONTROLLER_BUTTON_MISC1 = 15;
export const SDL_CONTROLLER_BUTTON_PADDLE1 = 16;
export const SDL_CONTROLLER_BUTTON_PADDLE2 = 17;
export const SDL_CONTROLLER_BUTTON_PADDLE3 = 18;
export const SDL_CONTROLLER_BUTTON_PADDLE4 = 19;
export const SDL_CONTROLLER_BUTTON_TOUCHPAD = 20;
export const SDL_CONTROLLER_BUTTON_MAX = 21;

export const SDL_CONTROLLER_AXIS_INVALID = -1;
export const SDL_CONTROLLER_AXIS_LEFTX = 0;
export const SDL_CONTROLLER_AXIS_LEFTY = 1;
export const SDL_CONTROLLER_AXIS_RIGHTX = 2;
export const SDL_CONTROLLER_AXIS_RIGHTY = 3;
export const SDL_CONTROLLER_AXIS_TRIGGERLEFT = 4;
export const SDL_CONTROLLER_AXIS_TRIGGERRIGHT = 5;
export const SDL_CONTROLLER_AXIS_MAX = 6;

export const SDL_HINT_AUTO_UPDATE_JOYSTICKS = "SDL_AUTO_UPDATE_JOYSTICKS";
export const SDL_HINT_AUTO_UPDATE_SENSORS = "SDL_AUTO_UPDATE_SENSORS";
export const SDL_HINT_ENABLE_STEAM_CONTROLLERS = "SDL_ENABLE_STEAM_CONTROLLERS";
export const SDL_HINT_GAMECONTROLLERCONFIG = "SDL_GAMECONTROLLERCONFIG";
export const SDL_HINT_GAMECONTROLLERCONFIG_FILE = "SDL_GAMECONTROLLERCONFIG_FILE";
export const SDL_HINT_GAMECONTROLLERTYPE = "SDL_GAMECONTROLLERTYPE";
export const SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES = "SDL_GAMECONTROLLER_IGNORE_DEVICES";
export const SDL_HINT_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT = "SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT";
export const SDL_HINT_GAMECONTROLLER_USE_BUTTON_LABELS = "SDL_GAMECONTROLLER_USE_BUTTON_LABELS";
export const SDL_HINT_HIDAPI_IGNORE_DEVICES = "SDL_HIDAPI_IGNORE_DEVICES";
export const SDL_HINT_JOYSTICK_ALLOW_BACKGROUND_EVENTS = "SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS";
export const SDL_HINT_JOYSTICK_HIDAPI = "SDL_JOYSTICK_HIDAPI";
export const SDL_HINT_JOYSTICK_HIDAPI_CORRELATE_XINPUT = "SDL_JOYSTICK_HIDAPI_CORRELATE_XINPUT";
export const SDL_HINT_JOYSTICK_HIDAPI_GAMECUBE = "SDL_JOYSTICK_HIDAPI_GAMECUBE";
export const SDL_HINT_JOYSTICK_GAMECUBE_RUMBLE_BRAKE = "SDL_JOYSTICK_GAMECUBE_RUMBLE_BRAKE";
export const SDL_HINT_JOYSTICK_HIDAPI_JOY_CONS = "SDL_JOYSTICK_HIDAPI_JOY_CONS";
export const SDL_HINT_JOYSTICK_HIDAPI_JOYCON_HOME_LED = "SDL_JOYSTICK_HIDAPI_JOYCON_HOME_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_COMBINE_JOY_CONS = "SDL_JOYSTICK_HIDAPI_COMBINE_JOY_CONS";
export const SDL_HINT_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS = "SDL_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS";
export const SDL_HINT_JOYSTICK_HIDAPI_LUNA = "SDL_JOYSTICK_HIDAPI_LUNA";
export const SDL_HINT_JOYSTICK_HIDAPI_NINTENDO_CLASSIC = "SDL_JOYSTICK_HIDAPI_NINTENDO_CLASSIC";
export const SDL_HINT_JOYSTICK_HIDAPI_SHIELD = "SDL_JOYSTICK_HIDAPI_SHIELD";
export const SDL_HINT_JOYSTICK_HIDAPI_PS3 = "SDL_JOYSTICK_HIDAPI_PS3";
export const SDL_HINT_JOYSTICK_HIDAPI_PS4 = "SDL_JOYSTICK_HIDAPI_PS4";
export const SDL_HINT_JOYSTICK_HIDAPI_PS4_RUMBLE = "SDL_JOYSTICK_HIDAPI_PS4_RUMBLE";
export const SDL_HINT_JOYSTICK_HIDAPI_PS5 = "SDL_JOYSTICK_HIDAPI_PS5";
export const SDL_HINT_JOYSTICK_HIDAPI_PS5_PLAYER_LED = "SDL_JOYSTICK_HIDAPI_PS5_PLAYER_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_PS5_RUMBLE = "SDL_JOYSTICK_HIDAPI_PS5_RUMBLE";
export const SDL_HINT_JOYSTICK_HIDAPI_STADIA = "SDL_JOYSTICK_HIDAPI_STADIA";
export const SDL_HINT_JOYSTICK_HIDAPI_STEAM = "SDL_JOYSTICK_HIDAPI_STEAM";
export const SDL_HINT_JOYSTICK_HIDAPI_SWITCH = "SDL_JOYSTICK_HIDAPI_SWITCH";
export const SDL_HINT_JOYSTICK_HIDAPI_SWITCH_HOME_LED = "SDL_JOYSTICK_HIDAPI_SWITCH_HOME_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED = "SDL_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_WII = "SDL_JOYSTICK_HIDAPI_WII";
export const SDL_HINT_JOYSTICK_HIDAPI_WII_PLAYER_LED = "SDL_JOYSTICK_HIDAPI_WII_PLAYER_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX = "SDL_JOYSTICK_HIDAPI_XBOX";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX_360 = "SDL_JOYSTICK_HIDAPI_XBOX_360";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED = "SDL_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX_360_WIRELESS = "SDL_JOYSTICK_HIDAPI_XBOX_360_WIRELESS";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE = "SDL_JOYSTICK_HIDAPI_XBOX_ONE";
export const SDL_HINT_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED = "SDL_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED";
export const SDL_HINT_JOYSTICK_RAWINPUT = "SDL_JOYSTICK_RAWINPUT";
export const SDL_HINT_JOYSTICK_RAWINPUT_CORRELATE_XINPUT = "SDL_JOYSTICK_RAWINPUT_CORRELATE_XINPUT";
export const SDL_HINT_JOYSTICK_ROG_CHAKRAM = "SDL_JOYSTICK_ROG_CHAKRAM";
export const SDL_HINT_JOYSTICK_THREAD = "SDL_JOYSTICK_THREAD";
export const SDL_HINT_JOYSTICK_DEVICE = "SDL_JOYSTICK_DEVICE";

export const SDL_INIT_GAMECONTROLLER = 0x00002000;